services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: accountapp
      POSTGRES_PASSWORD: accountapp
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - database_net

networks:
  database_net:
    driver: bridge

volumes:
  postgres:
  pgadmin: